# Site settings
title: Meijioo Blog
baseurl: ""
url: "http://meijioo.github.io"
github_username:meijioo

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
